export const RESERVATION_DELETE_RESET = 'RESERVATION_DELETE_RESET'
export const RESERVATION_DELETE_SET_ERROR = 'RESERVATION_DELETE_SET_ERROR'
export const RESERVATION_DELETE_SET_DELETED = 'RESERVATION_DELETE_SET_DELETED'
export const RESERVATION_DELETE_TOGGLE_LOADING = 'RESERVATION_DELETE_TOGGLE_LOADING'
