export const ROOM_DELETE_RESET = 'ROOM_DELETE_RESET'
export const ROOM_DELETE_SET_ERROR = 'ROOM_DELETE_SET_ERROR'
export const ROOM_DELETE_SET_DELETED = 'ROOM_DELETE_SET_DELETED'
export const ROOM_DELETE_TOGGLE_LOADING = 'ROOM_DELETE_TOGGLE_LOADING'
