export const COMMENT_SHOW_RESET = 'COMMENT_SHOW_RESET'
export const COMMENT_SHOW_SET_ERROR = 'COMMENT_SHOW_SET_ERROR'
export const COMMENT_SHOW_SET_RETRIEVED = 'COMMENT_SHOW_SET_RETRIEVED'
export const COMMENT_SHOW_TOGGLE_LOADING = 'COMMENT_SHOW_TOGGLE_LOADING'
