export const REGION_SHOW_RESET = 'REGION_SHOW_RESET'
export const REGION_SHOW_SET_ERROR = 'REGION_SHOW_SET_ERROR'
export const REGION_SHOW_SET_RETRIEVED = 'REGION_SHOW_SET_RETRIEVED'
export const REGION_SHOW_TOGGLE_LOADING = 'REGION_SHOW_TOGGLE_LOADING'
