export const RESERVATION_SHOW_RESET = 'RESERVATION_SHOW_RESET'
export const RESERVATION_SHOW_SET_ERROR = 'RESERVATION_SHOW_SET_ERROR'
export const RESERVATION_SHOW_SET_RETRIEVED = 'RESERVATION_SHOW_SET_RETRIEVED'
export const RESERVATION_SHOW_TOGGLE_LOADING = 'RESERVATION_SHOW_TOGGLE_LOADING'
