export const CLIENT_SHOW_RESET = 'CLIENT_SHOW_RESET'
export const CLIENT_SHOW_SET_ERROR = 'CLIENT_SHOW_SET_ERROR'
export const CLIENT_SHOW_SET_RETRIEVED = 'CLIENT_SHOW_SET_RETRIEVED'
export const CLIENT_SHOW_TOGGLE_LOADING = 'CLIENT_SHOW_TOGGLE_LOADING'
