export const OWNER_DELETE_RESET = 'OWNER_DELETE_RESET'
export const OWNER_DELETE_SET_ERROR = 'OWNER_DELETE_SET_ERROR'
export const OWNER_DELETE_SET_DELETED = 'OWNER_DELETE_SET_DELETED'
export const OWNER_DELETE_TOGGLE_LOADING = 'OWNER_DELETE_TOGGLE_LOADING'
