export const STAFF_DELETE_RESET = 'STAFF_DELETE_RESET'
export const STAFF_DELETE_SET_ERROR = 'STAFF_DELETE_SET_ERROR'
export const STAFF_DELETE_SET_DELETED = 'STAFF_DELETE_SET_DELETED'
export const STAFF_DELETE_TOGGLE_LOADING = 'STAFF_DELETE_TOGGLE_LOADING'
