export const REGION_DELETE_RESET = 'REGION_DELETE_RESET'
export const REGION_DELETE_SET_ERROR = 'REGION_DELETE_SET_ERROR'
export const REGION_DELETE_SET_DELETED = 'REGION_DELETE_SET_DELETED'
export const REGION_DELETE_TOGGLE_LOADING = 'REGION_DELETE_TOGGLE_LOADING'
