export const COMMENT_DELETE_RESET = 'COMMENT_DELETE_RESET'
export const COMMENT_DELETE_SET_ERROR = 'COMMENT_DELETE_SET_ERROR'
export const COMMENT_DELETE_SET_DELETED = 'COMMENT_DELETE_SET_DELETED'
export const COMMENT_DELETE_TOGGLE_LOADING = 'COMMENT_DELETE_TOGGLE_LOADING'
