export const STAFF_SHOW_RESET = 'STAFF_SHOW_RESET'
export const STAFF_SHOW_SET_ERROR = 'STAFF_SHOW_SET_ERROR'
export const STAFF_SHOW_SET_RETRIEVED = 'STAFF_SHOW_SET_RETRIEVED'
export const STAFF_SHOW_TOGGLE_LOADING = 'STAFF_SHOW_TOGGLE_LOADING'
