export const OWNER_SHOW_RESET = 'OWNER_SHOW_RESET'
export const OWNER_SHOW_SET_ERROR = 'OWNER_SHOW_SET_ERROR'
export const OWNER_SHOW_SET_RETRIEVED = 'OWNER_SHOW_SET_RETRIEVED'
export const OWNER_SHOW_TOGGLE_LOADING = 'OWNER_SHOW_TOGGLE_LOADING'
