export const ROOM_SHOW_RESET = 'ROOM_SHOW_RESET'
export const ROOM_SHOW_SET_ERROR = 'ROOM_SHOW_SET_ERROR'
export const ROOM_SHOW_SET_RETRIEVED = 'ROOM_SHOW_SET_RETRIEVED'
export const ROOM_SHOW_TOGGLE_LOADING = 'ROOM_SHOW_TOGGLE_LOADING'
